### ISSUE TITLE
create  h1 on footer

### ISSUE THREAD

**Issue by CarolinaCedro** [CarolinaCedro/Landing-Page-React#13]
create h1 on footer

**Comment by PaxtonDevs** [comment]
Hello, I'd like to be assigned this task

**Comment by CarolinaCedro** [comment]
@PaxtonDevs  done men

**Comment by PaxtonDevs** [comment]
Issue has been completed. Would appreciate the "hacktoberfest-accepted" label on the issue before merging. Thank you

**Comment by CarolinaCedro** [comment]
I saw just now about the new tag sorry

**Comment by CarolinaCedro** [comment]
as ok
